export const SET_USER_SETTINGS_SUCCESS = "SET_USER_SETTINGS_SUCCESS";
export const SET_USER_SETTINGS_FAILED = "SET_USER_SETTINGS_FAILED";

export const GET_USER_SETTINGS_SUCCESS = "GET_USER_SETTINGS_SUCCESS";

export const ADD_USER_WORKING_HOUR = "ADD_USER_WORKING_HOUR";
export const USER_NEW_LEVEL = "USER_NEW_LEVEL";
export const SHOW_OPTIONS_TO_NEW_USER = "SHOW_OPTIONS_TO_NEW_USER";
