export const SET_USER_SETTINGS_SUCCESS = 'SET_USER_SETTINGS_SUCCESS';
export const SET_USER_SETTINGS_FAILED = 'SET_USER_SETTINGS_FAILED';
export const GET_USER_SETTINGS_SUCCESS = 'GET_USER_SETTINGS_SUCCESS';
